apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: browser-game

commonLabels:
  app.kubernetes.io/name: browser-game-laravel
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - nginx-configmap.yaml
  - deployment.yaml
  - mysql-statefulset.yaml
  - redis.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
